apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: timestamp-authority-release-next
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: timestamp-authority-release-next
    app.kubernetes.io/part-of: timestamp-authority
  name: timestamp-authority-release-next
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: timestamp-authority-release-next
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: timestamp-authority-release-next
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/timestamp-authority/timestamp-authority-release-next@sha256:7ed9f988cb419e00977f63740c59b429495c8f8678fb2d1630c449e6c52834c6
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
status: {}
