apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: timestamp-authority-release-next
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: timestamp-authority-release-next
    app.kubernetes.io/part-of: timestamp-authority
  name: timestamp-authority-release-next
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: timestamp-authority-release-next
status:
  loadBalancer: {}
